#!/bin/sh
# Universal post-create script for devcontainer environments
# Works across TypeScript, JavaScript, Python, and other project types

set -e  # Exit on error

# ============================================================================
# Configuration Variables
# ============================================================================

# Workspace root (project directory)
WORKSPACE_ROOT="${WORKSPACE_ROOT:-$PWD}"

# SSH configuration
SSH_CONTEXT="${SSH_CONTEXT:-default}"

# Chezmoi dotfiles repository
CHEZMOI_DOTFILES_REPOSITORY="${CHEZMOI_DOTFILES_REPOSITORY:-git@github.com:/${GITHUB_USERNAME}/devcontainer-dotfiles}"

# AI agent templates source directory
AGENT_SOURCE_DIR="${WORKSPACE_ROOT}/docs/ai-dev-rules/agents"

# AI agent target directories (space-separated)
AGENT_TARGETS="${WORKSPACE_ROOT}/.github/agents ${WORKSPACE_ROOT}/.amazonq/agents"

# ============================================================================
# SSH Setup
# ============================================================================

echo "Setting up SSH configuration..."

# Fix SSH directory ownership (mounted as root in Dockerfile)
if [ -d "$HOME/.ssh" ]; then
  sudo chown -R "$USER":"$USER" "$HOME/.ssh"
fi

# Create SSH config with context-specific configuration
cat >"$HOME/.ssh/config" <<EOF
# ===== AUTOGENERATED =====
Include $HOME/.ssh/contexts/$SSH_CONTEXT/config
Host *
  IdentitiesOnly yes
  ServerAliveInterval 60
EOF

echo "✓ SSH configuration complete"

# ============================================================================
# Chezmoi Setup
# ============================================================================

echo "Setting up chezmoi configuration..."

# Create chezmoi config directory
mkdir -p "$HOME/.config/chezmoi"

# Move chezmoi config from Dockerfile location
if [ -f "/usr/src/chezmoi.toml" ]; then
  sudo mv /usr/src/chezmoi.toml "$HOME/.config/chezmoi/chezmoi.toml"
  sudo chown -R "$USER":"$USER" "$HOME/.config/chezmoi"
  echo "✓ Chezmoi config moved from /usr/src"
else
  echo "Warning: /usr/src/chezmoi.toml not found, skipping"
fi

# ============================================================================
# Dotfiles Setup
# ============================================================================

echo "Setting up dotfiles..."

if [ -z "$GITHUB_USERNAME" ]; then
  echo "Warning: GITHUB_USERNAME not set, skipping dotfiles setup"
else
  echo "Initializing dotfiles from: $CHEZMOI_DOTFILES_REPOSITORY"
  chezmoi init --apply "${CHEZMOI_DOTFILES_REPOSITORY}" || {
    echo "Warning: Failed to initialize dotfiles, continuing..."
  }
  echo "✓ Dotfiles initialized"
fi

# ============================================================================
# ZSH Configuration
# ============================================================================

echo "Setting up ZSH configuration..."

# FIXME: We're first copying the .zshrc file to the home directory via chezmoi,
# but now we're backing it up and linking it to a mounted location.
# This should be refactored to avoid the double-copy.

# Backup existing .zshrc if it exists
if [ -f "$HOME/.zshrc" ]; then
  mv "$HOME/.zshrc" "$HOME/.zshrc.bak"
  echo "✓ Backed up existing .zshrc"
fi

# Link to mounted zsh configuration
if [ -d "$HOME/.config/zsh" ] && [ -f "$HOME/.config/zsh/.zshrc" ]; then
  ln -sf "$HOME/.config/zsh/.zshrc" "$HOME/.zshrc"
  echo "✓ Linked ZSH configuration from $HOME/.config/zsh"
else
  echo "Warning: $HOME/.config/zsh/.zshrc not found, skipping symlink"
fi

# ============================================================================
# AI Agent Templates Setup
# ============================================================================

echo "Setting up AI agent templates..."

# Check if agent source directory exists
if [ ! -d "$AGENT_SOURCE_DIR" ]; then
  echo "Info: Agent source directory not found: $AGENT_SOURCE_DIR"
  echo "Skipping agent template setup (not all projects have ai-dev-rules)"
else
  # Count agent files
  agent_count=$(find "$AGENT_SOURCE_DIR" -maxdepth 1 -name "*.agent.md" -type f 2>/dev/null | wc -l | tr -d ' ')
  
  if [ "$agent_count" -eq 0 ]; then
    echo "Info: No .agent.md files found in $AGENT_SOURCE_DIR"
    echo "Skipping agent template setup"
  else
    echo "Found $agent_count agent template(s)"
    
    # Create target directories and symlink each agent file
    for target_dir in $AGENT_TARGETS; do
      mkdir -p "$target_dir"
      
      # Symlink each agent file
      for agent_file in "$AGENT_SOURCE_DIR"/*.agent.md; do
        [ -f "$agent_file" ] || continue  # Skip if no matches
        agent_name=$(basename "$agent_file")
        
        # Remove existing symlink/file if it exists
        [ -e "$target_dir/$agent_name" ] && rm -f "$target_dir/$agent_name"
        
        ln -sf "$agent_file" "$target_dir/$agent_name"
      done
      
      echo "✓ Symlinked agents to $(basename "$target_dir")"
    done
  fi
fi

# ============================================================================
# Project-Specific Setup (Optional)
# ============================================================================

# Check for project-specific post-create script
PROJECT_POST_CREATE="${WORKSPACE_ROOT}/.devcontainer/post_create_project.sh"

if [ -f "$PROJECT_POST_CREATE" ]; then
  echo "Running project-specific post-create script..."
  chmod +x "$PROJECT_POST_CREATE"
  "$PROJECT_POST_CREATE"
  echo "✓ Project-specific setup complete"
fi

# ============================================================================
# Completion
# ============================================================================

echo ""
echo "========================================="
echo "✓ Devcontainer setup complete!"
echo "========================================="
echo ""
echo "Environment details:"
echo "  Workspace: $WORKSPACE_ROOT"
echo "  User: $USER"
echo "  SSH Context: $SSH_CONTEXT"
echo ""
